version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cnqeswe9x2ez"
s3_prefix = "sam-app"
region = "us-east-1"
profile = "multithreadlabs-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"example\" Environment=\"dev\" UserPoolARN=\"arn:aws:cognito-idp:us-east-1:921906086636:userpool/us-east-1_psrGngUkB\""
