AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Node AWS SAM application Integrates with Terraform deployed infrastructure
Parameters:
  AppName:
    Type: String
    Description: Name of application (no spaces). Value must be globally unique
    Default: example
  Environment:
    Type: String
    Description: Name of application (no spaces). Value must be globally unique
    Default: dev
  IdentityRoleARN:
    Type: String
    Description: Identity lambda Role ARN
  UserRoleARN:
    Type: String
    Description: User lambda Role ARN
  UserReceiverRoleARN:
    Type: String
  SNSTopicARN:
    Type: String
    Description: SNS Topic ARN for UserFunction to publish messages on SNS
  DebugSampleRate:
    Type: Number
    Description: Percentage of debug logging printed to CloudWatch on Production environment
    Default: 0.05
  CognitoUserPoolClientID:
    Type: String
  CognitoUserPoolID:
    Type: String
  CognitoUserPoolARN:
    Type: String
  APITimeout:
    Type: Number
    Description: Sets the timeout in millis for all API endpoints
    Default: 4000
Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Runtime: nodejs12.x
    Timeout: 4
    ReservedConcurrentExecutions: 10
    MemorySize: 256
    AutoPublishAlias: live
    Tracing: Active
    Layers:
    - Ref: LambdaLayer
    Tags:
      Environment:
        Ref: Environment
      Name:
        Ref: AppName
Resources:

  # API Gateway
  Api:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration: EDGE
      StageName: dev
      TracingEnabled: true
      MethodSettings:
      - HttpMethod: '*'
        ResourcePath: /*
        DataTraceEnabled: true
        LoggingLevel: ERROR
        MetricsEnabled: true
        ThrottlingBurstLimit: 10
        ThrottlingRateLimit: 20
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: api.yaml
      Tags:
        Environment:
          Ref: Environment
        Name:
          Ref: AppName

  # Lambda Functions
  IdentityFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-identity
      Description: Provides all Cognito functions through 4 API Rest calls
      CodeUri: src/
      Handler: identity/app.lambdaHandler
      Role:
        Ref: IdentityRoleARN
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
        - Ref: IdentityCanaryErrorsAlarm
      Environment:
        Variables:
          COGNITO_USER_POOL_CLIENT_ID:
            Ref: CognitoUserPoolClientID
          COGNITO_USER_POOL_ID:
            Ref: CognitoUserPoolID
          DEBUG_SAMPLE_RATE:
            Ref: DebugSampleRate

  UserFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-user
      Description: Provides all User functions
      CodeUri: src/
      Handler: user/app.lambdaHandler
      Role:
        Ref: UserRoleARN
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
        - Ref: UserCanaryErrorsAlarm
      Environment:
        Variables:
          DEBUG_SAMPLE_RATE:
            Ref: DebugSampleRate
          SNS_TOPIC:
            Ref: SNSTopicARN

  UserReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${Environment}-${AppName}-user-receiver
      Description: Integrated with SNS
      CodeUri: src/
      Handler: user_receiver/app.lambdaHandler
      Role:
        Ref: UserReceiverRoleARN
      DeploymentPreference:
        Type: Canary10Percent5Minutes
        Alarms:
        - Ref: UserReceiverCanaryErrorsAlarm
      Environment:
        Variables:
          DEBUG_SAMPLE_RATE:
            Ref: DebugSampleRate

  # Lambda Layer
  LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName:
        Fn::Sub: ${Environment}-${AppName}-layer
      Description:
        Fn::Sub: Lambda layer for ${Environment}-${AppName}-layer application
      ContentUri: dependencies
      CompatibleRuntimes:
      - nodejs12.x
      RetentionPolicy: Retain
  
  # CloudWatch Alarms
  IdentityCanaryErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ${Environment}-${AppName}-identity-canary-alarm
      AlarmDescription: Identity Lambda function canary errors
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
      Dimensions:
        - Name: Resource
          Value:
            Fn::Sub: ${IdentityFunction}:live
        - Name: FunctionName
          Value: 
            Ref: IdentityFunction
        - Name: ExecutedVersion
          Value:
            Fn::GetAtt:
            - IdentityFunction
            - Version
            - Version
  UserCanaryErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ${Environment}-${AppName}-user-canary-alarm
      AlarmDescription: User Lambda function canary errors
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
      Dimensions:
        - Name: Resource
          Value:
            Fn::Sub: ${UserFunction}:live
        - Name: FunctionName
          Value: 
            Ref: UserFunction
        - Name: ExecutedVersion
          Value:
            Fn::GetAtt:
            - UserFunction
            - Version
            - Version
  UserReceiverCanaryErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ${Environment}-${AppName}-user-receiver-canary-alarm
      AlarmDescription: UserReceiver Lambda function canary errors
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 2
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
      Dimensions:
        - Name: Resource
          Value:
            Fn::Sub: ${UserReceiverFunction}:live
        - Name: FunctionName
          Value: 
            Ref: UserReceiverFunction
        - Name: ExecutedVersion
          Value:
            Fn::GetAtt:
            - UserReceiverFunction
            - Version
            - Version
Outputs:
  ApiID:
    Description: API Gateway Resource ID
    Value:
      Ref: Api
  ApiURL:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev/
  IdentityFunction:
    Description: Identity Lambda Function ARN
    Value:
      Fn::GetAtt:
      - IdentityFunction
      - Arn
  UserFunction:
    Description: User Lambda Function ARN
    Value:
      Fn::GetAtt:
      - UserFunction
      - Arn
  UserReceiverFunction:
    Description: User receiver Lambda Function ARN
    Value:
      Fn::GetAtt:
      - UserReceiverFunction
      - Arn
